// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGoNhgJ5lOVZJWRdToQFBh-JECsO6vXO0',
    appId: '1:363806973749:web:87c7d0bf9c608d0a99767c',
    messagingSenderId: '363806973749',
    projectId: 'word-prime-a63df',
    authDomain: 'word-prime-a63df.firebaseapp.com',
    storageBucket: 'word-prime-a63df.firebasestorage.app',
    measurementId: 'G-HT7HQB5Y6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhnpLTm4zERdlnDHqJ6TexPhuL5ViGScI',
    appId: '1:363806973749:android:e978d51d2a237ba099767c',
    messagingSenderId: '363806973749',
    projectId: 'word-prime-a63df',
    storageBucket: 'word-prime-a63df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiqvaBObfdLBYnd-lxMRYsUluVIfldRjw',
    appId: '1:363806973749:ios:b57043da184cfcab99767c',
    messagingSenderId: '363806973749',
    projectId: 'word-prime-a63df',
    storageBucket: 'word-prime-a63df.firebasestorage.app',
    iosBundleId: 'com.hbd.wordPrime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiqvaBObfdLBYnd-lxMRYsUluVIfldRjw',
    appId: '1:363806973749:ios:b57043da184cfcab99767c',
    messagingSenderId: '363806973749',
    projectId: 'word-prime-a63df',
    storageBucket: 'word-prime-a63df.firebasestorage.app',
    iosBundleId: 'com.hbd.wordPrime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGoNhgJ5lOVZJWRdToQFBh-JECsO6vXO0',
    appId: '1:363806973749:web:97e9f1c6933eea7b99767c',
    messagingSenderId: '363806973749',
    projectId: 'word-prime-a63df',
    authDomain: 'word-prime-a63df.firebaseapp.com',
    storageBucket: 'word-prime-a63df.firebasestorage.app',
    measurementId: 'G-4L54H564C9',
  );
}
