// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbXoY8RTJgojJCydaN3rBX9dpAhjoVw58',
    appId: '1:212443500524:web:6013c514e30481018f7ac9',
    messagingSenderId: '212443500524',
    projectId: 'word-prime',
    authDomain: 'word-prime.firebaseapp.com',
    storageBucket: 'word-prime.firebasestorage.app',
    measurementId: 'G-D3SG5H3FGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJAHnlEH_RZXxuBAvbVU8tZzQ5ahITsg0',
    appId: '1:212443500524:android:8b9661baba96edc08f7ac9',
    messagingSenderId: '212443500524',
    projectId: 'word-prime',
    storageBucket: 'word-prime.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8VhND6isSpsYbomKP-JIoyqPbP4_FMa4',
    appId: '1:212443500524:ios:b0d1432d1ce0faf18f7ac9',
    messagingSenderId: '212443500524',
    projectId: 'word-prime',
    storageBucket: 'word-prime.firebasestorage.app',
    iosBundleId: 'com.hbd.wordPrime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8VhND6isSpsYbomKP-JIoyqPbP4_FMa4',
    appId: '1:212443500524:ios:b0d1432d1ce0faf18f7ac9',
    messagingSenderId: '212443500524',
    projectId: 'word-prime',
    storageBucket: 'word-prime.firebasestorage.app',
    iosBundleId: 'com.hbd.wordPrime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbXoY8RTJgojJCydaN3rBX9dpAhjoVw58',
    appId: '1:212443500524:web:d0522f9aaefe71f18f7ac9',
    messagingSenderId: '212443500524',
    projectId: 'word-prime',
    authDomain: 'word-prime.firebaseapp.com',
    storageBucket: 'word-prime.firebasestorage.app',
    measurementId: 'G-XPWXQPGKH0',
  );
}
